Download this dataset about cars:

Create an RDD using this dataset. (Make sure to exclude the first two rows.)

Create three sample RDDs from the RDD without replacement.

Two 10 percent samples.

One 20 percent sample.

Create an RDD containing distinct elements from two 10 percent sample RDDs. 

Create an RDD containing distinct elements from the 20 percent sample RDD.

Calculate how many elements are in both of the previous two RDDs from step 3. You CANNOT use any action operations, except for each and collect.

In [12]:
from pyspark import SparkContext
sc = SparkContext.getOrCreate()
cardata=sc.textFile("cars.csv").zipWithIndex().filter(lambda x:x[1]>0).map(lambda y:y[0])
sample1 = cardata.sample(False, 0.1)
sample2 = cardata.sample(False, 0.1)
sample3 = cardata.sample(False, 0.2)
distinct12 = sample1.union(sample2).distinct().collect()
# distinct2 = sample2.distinct().collect()
# disctinct3 = sample3.distinct().collect()
distinct12

['AMC Hornet Sportabout (sw),18,6,258,110,2962,13.5,71,US,90,NJ',
 'AMC Matador (sw),14,8,304,150,4257,15.5,74,US,185,OH',
 'BMW 320i,21.5,4,121,110,2600,12.8,77,Europe,287,TEXAS',
 'Chevrolet Caprice Classic,17,8,305,130,3840,15.4,79,US,330,NJ',
 'Chevrolet Malibu Classic (sw),19.2,8,267,125,3605,15,79,US,336,DALLAS',
 'Ford Escort 4W,34.4,4,98,65,2045,16.2,81,US,396,DALLAS',
 'Ford Mustang Cobra,23.6,4,140,0,2905,14.3,80,US,381,TEXAS',
 'Honda Accord,36,4,107,75,2205,14.5,82,Japan,427,OH',
 'Pontiac Grand Prix LJ,16,8,400,180,4220,11.1,77,US,274,DALLAS',
 'Pontiac Lemans V6,21.5,6,231,115,3245,15.4,79,US,325,OH',
 'AMC Gremlin,18,6,232,100,2789,15,73,US,152,NewYork',
 'AMC Matador,14,8,304,150,3672,11.5,73,US,131,TEXAS',
 'Chrysler Lebaron Town @ Country (sw),18.5,8,360,150,3940,13,79,US,337,OH',
 'Dodge Charger 2.2,36,4,135,84,2370,13,82,US,75,TEXAS',
 'Ford Gran Torino (sw),13,8,302,140,4294,16,72,US,119,NewYork',
 'Chevrolet Malibu,20.5,6,200,95,3155,18.2,78,US,298,NJ',
 'Ford Maverick,21,6,200,0,2875,17,74,US,171,TEXAS',
 'Plymouth Fury Gran Sedan,14,8,318,150,4237,14.5,73,US,138,TEXAS',
 'Saab 99e,25,4,104,95,2375,17.5,70,Europe,66,OH',
 'Volkswagen Jetta,33,4,105,74,2190,14.2,81,Europe,398,TEXAS',
 'Volkswagen Rabbit,29,4,90,70,1937,14,75,Europe,220,NJ',
 'Chevrolet Monte Carlo S,15,8,350,145,4082,13,73,US,160,TEXAS',
 'Datsun PL510,27,4,97,88,2130,14.5,70,Japan,62,OH',
 'Dodge St. Regis,18.2,8,318,135,3830,15.2,79,US,333,OH',
 'Ford Fiesta,36.1,4,98,66,1800,14.4,78,US,290,DALLAS',
 'Ford Pinto,19,4,122,85,2310,18.5,73,US,157,NewYork',
 'Oldsmobile Cutlass Salon Brougham,23.9,8,260,90,3420,22.2,79,US,345,NewYork',
 "Plymouth 'Cuda 340,14,8,340,160,3609,8,70,US,44,DALLAS",
 'Plymouth Duster,20,6,198,95,3102,16.5,74,US,170,NJ',
 'Plymouth Valiant Custom,19,6,225,95,3264,16,75,US,197,OH',
 'Renault 12 (sw),26,4,96,69,2189,18,72,Europe,124,NJ',
 'Toyota Corolla,32.4,4,108,75,2350,16.8,81,Japan,401,NewYork',
 'Volkswagen Scirocco,31.5,4,89,71,1990,14.9,78,Europe,323,DALLAS',
 'AMC Matador,15.5,8,304,120,3962,13.9,76,US,234,DALLAS',
 'AMC Pacer,19,6,232,90,3211,17,75,US,221,NewYork',
 'Buick Estate Wagon (sw),14,8,455,225,3086,10,70,US,57,NJ',
 'Chevy C20,10,8,307,200,4376,15,70,US,70,NJ',
 'Datsun 200SX,32.9,4,119,100,2615,14.8,81,Japan,402,OH',
 'Fiat 124 TC,26,4,116,75,2246,14,74,Europe,193,NJ',
 'Fiat 124B,30,4,88,76,2065,14.5,71,Europe,97,DALLAS',
 'Ford Torino (sw),0,8,351,153,4034,11,70,US,56,NewYork',
 'Mercedes-Benz 280s,16.5,6,168,120,3820,16.7,76,Europe,256,TEXAS',
 'Peugeot 504,23,4,120,88,2957,17,75,Europe,74,TEXAS',
 'Peugeot 604sl,16.2,6,163,133,3410,15.8,78,Europe,322,TEXAS',
 'Plymouth Satellite Custom (sw),14,8,318,150,4077,14,72,US,120,NewYork',
 'Plymouth Valiant,18,6,225,105,3121,16.5,73,US,142,DALLAS',
 'Toyota Corolla 1200,31,4,71,65,1773,19,71,Japan,98,DALLAS',
 'Volkswagen Rabbit C (Diesel),44.3,4,90,48,2085,21.7,80,Europe,370,NJ',
 'Buick Century 350,13,8,350,175,4100,13,73,US,130,NJ',
 'Chevrolet Impala,14,8,454,220,4354,9,70,US,7,NJ',
 'Chevrolet Malibu,13,8,350,145,3988,13,73,US,132,NewYork',
 'Chevrolet Monte Carlo Landau,19.2,8,305,145,3425,13.2,78,US,307,DALLAS',
 'Ford F108,13,8,302,130,3870,15,76,US,259,NewYork',
 'Mercury Monarch ghia,20.2,8,302,139,3570,12.8,78,US,296,DALLAS',
 'Plymouth Sapporo,23.2,4,156,105,2745,16.7,78,US,316,NJ',
 'Saab 99le,24,4,121,110,2660,14,73,Europe,167,NJ',
 'Subaru,26,4,108,93,2391,15.5,74,Japan,195,TEXAS',
 'AMC Ambassador SST,17,8,304,150,3672,11.5,72,US,4,DALLAS',
 'AMC Pacer d/l,17.5,6,258,95,3193,17.8,76,US,75,NJ',
 'Buick Electra 225 Custom,12,8,455,225,4951,11,73,US,140,NewYork',
 'Chevrolet Chevelle Malibu Classic,16,6,250,100,3781,17,74,US,178,NJ',
 'Chevrolet Nova Custom,16,6,250,100,3278,18,73,US,143,TEXAS',
 'Chevrolet Woody,24.5,4,98,60,2164,22.1,76,US,241,OH',
 'Chrysler Newport Royal,13,8,400,190,4422,12.5,72,US,115,NJ',
 'Datsun 1200,35,4,72,69,1613,18,71,Japan,99,TEXAS',
 'Ford Fairmont (auto),20.2,6,200,85,2965,15.8,78,US,299,TEXAS',
 'Ford Fairmont (man),25.1,4,140,88,2720,15.4,78,US,300,OH',
 'Ford Gran Torino,14,8,302,137,4042,14.5,73,US,133,DALLAS',
 'Ford Torino,17,8,302,140,3449,10.5,70,US,5,OH',
 'Plymouth Arrow GS,25.5,4,122,96,2300,15.5,77,US,75275,OH',
 'Plymouth Duster,22,6,198,95,2833,15.5,70,US,59,OH',
 'Plymouth Volare,20.5,6,225,100,3430,17.2,78,US,301,NewYork',
 'Pontiac Catalina Brougham,14,8,400,175,4464,11.5,71,US,84,OH',
 'Buick Regal Sport Coupe (turbo),17.7,6,231,165,3445,13.4,78,US,308,NewYork',
 'Buick Skylark 320,15,8,350,165,3693,11.5,70,US,25,NJ',
 'Chevrolet Citation,23.5,6,173,110,2725,12.6,81,US,386,OH',
 'Chevrolete Chevelle Malibu,16,6,250,105,3897,18.5,75,US,206,NewYork',
 'Chevy S-10,31,4,119,82,2720,19.4,82,US,7,NewYork',
 'Datsun 710,24,4,119,97,2545,17,75,Japan,218,DALLAS',
 'Fiat Strada Custom,37.3,4,91,69,2130,14.7,79,Europe,349,NJ',
 'Ford Futura,18.1,8,302,139,3205,11.2,78,US,57,TEXAS',
 'Oldsmobile Delta 88 Royale,12,8,350,160,4456,13.5,72,US,114,DALLAS',
 'Volkswagen Rabbit Custom,29,4,97,78,1940,14.5,77,Europe,278,DALLAS']

We will use the same dataset from the previous Exercises (cars.csv).

Create an RDD using this dataset. (Make sure to exclude the first two rows.)

Calculate the following about the cars:
* Total Weight.
* Average MPG.
* How many cars we have for each Origin.